name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --repo-update || true

    - name: Set Default Scheme
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV
        echo "Using default scheme: $default"

    - name: Disable code signing in Xcode project
      run: |
        /usr/libexec/PlistBuddy -c "Set :CODE_SIGN_IDENTITY \"\"" "MASTestApp.xcodeproj/project.pbxproj"
        /usr/libexec/PlistBuddy -c "Set :PROVISIONING_PROFILE_SPECIFIER \"\"" "MASTestApp.xcodeproj/project.pbxproj"
        /usr/libexec/PlistBuddy -c "Set :DEVELOPMENT_TEAM \"\"" "MASTestApp.xcodeproj/project.pbxproj"
        /usr/libexec/PlistBuddy -c "Set :CODE_SIGN_STYLE Manual" "MASTestApp.xcodeproj/project.pbxproj"

    - name: Build the app (unsigned)
      run: |
        xcodebuild clean archive \
          -project "MASTestApp.xcodeproj" \
          -scheme $DEFAULT_SCHEME \
          -configuration Release \
          -archivePath $GITHUB_WORKSPACE/build/MASTestApp.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          OTHER_CODE_SIGN_FLAGS="--deep --force --sign -"

    - name: Export IPA (unsigned)
      run: |
        mkdir -p output
        xcodebuild -exportArchive \
          -archivePath $GITHUB_WORKSPACE/build/MASTestApp.xcarchive \
          -exportPath output \
          -exportOptionsPlist ExportOptionsUnsigned.plist \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=""

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unsigned-iOS-App
        path: output/*.ipa