name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --repo-update || true

    - name: Set iOS Deployment Target to 14.4
      run: |
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 14.4;/g' MASTestApp.xcodeproj/project.pbxproj
        echo "Deployment target set to 14.4"

    - name: Set Default Scheme
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV
        echo "Using default scheme: $default"

    - name: Build the app (unsigned)
      run: |
        xcodebuild archive \
          -project "MASTestApp.xcodeproj" \
          -scheme "$DEFAULT_SCHEME" \
          -archivePath "$GITHUB_WORKSPACE/build/MASTestApp.xcarchive" \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Add Entitlements
      run: |
        ldid -Sentitlements.plist "$GITHUB_WORKSPACE/build/MASTestApp.xcarchive/Products/Applications/MASTestApp.app/MASTestApp"

    - name: Create IPA manually
      run: |
        cd "$GITHUB_WORKSPACE/build/MASTestApp.xcarchive/Products" || exit
        mv Applications Payload
        zip -r9q MASTestApp.zip Payload
        mv MASTestApp.zip MASTestApp.ipa
        mkdir -p "$GITHUB_WORKSPACE/output"
        mv MASTestApp.ipa "$GITHUB_WORKSPACE/output/MASTestApp-unsigned.ipa"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unsigned-iOS-App
        path: output/MASTestApp.ipa
