name: Appium Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      BUNDLE_IDENTIFIER: org.owasp.mastestapp.MASTestApp-iOS
      PLATFORM: "iOS Simulator"
      SIMULATOR: "iPhone 16"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Appium and Python Dependencies
        run: |
          npm install -g appium
          python3 -m pip install --break-system-packages Appium-Python-Client
      
      - name: Install Appium Driver for XCUITest
        run: |
          appium driver install xcuitest

      - name: Start Appium Server
        run: |
          # Start Appium in the background and give it a few seconds to initialize
          appium & 
          # sleep 10

      - name: Install Dependencies
        run: |
          brew install ldid || true
          brew install cocoapods || true
          if [ -f Podfile ]; then
            pod install --repo-update || true
          fi

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo "$scheme_list" | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV
          echo "Using default scheme: $default"

      - name: Build App for Simulator
        run: |
          if ls -A | grep -iq "\.xcworkspace$"; then
            filetype_parameter="workspace"
            file_to_build=$(ls -A | grep -i "\.xcworkspace$")
          else
            filetype_parameter="project"
            file_to_build=$(ls -A | grep -i "\.xcodeproj$")
          fi
          file_to_build=$(echo "$file_to_build" | awk '{$1=$1;print}')
          # Build for simulator with code signing disabled
          xcodebuild build \
            -scheme "$DEFAULT_SCHEME" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=$PLATFORM,name=$SIMULATOR" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Boot Simulator
        run: |
          # Boot the selected simulator if not already booted
          xcrun simctl boot "$SIMULATOR" || echo "Simulator already booted"
          # Allow time for the simulator to finish booting
          sleep 10

      - name: Install and Launch App on Simulator
        run: |
          # Locate the built .app from DerivedData
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "Error: Could not find the built .app file."
            exit 1
          fi
          echo "Installing app from: $APP_PATH"
          xcrun simctl install "$SIMULATOR" "$APP_PATH"
          echo "Launching app with bundle identifier $BUNDLE_IDENTIFIER"
          xcrun simctl launch "$SIMULATOR" "$BUNDLE_IDENTIFIER"

      - name: Capture Screenshot
        run: |
          # Wait for the app to fully launch before taking a screenshot
          sleep 10
          xcrun simctl io "$SIMULATOR" screenshot screenshot.png

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Screenshot
          path: screenshot.png

      - name: Run Appium UI Test
        # env: # currently not working so we attach to the running app instead
          # Pass the built app's path to the test script; Appium requires the .app folder.
          # APP_PATH: "build/MASTestApp.xcarchive/Products/Applications/MASTestApp.app"
        run: |
          python3 tools/appium_script.py

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UI-Test-Artifacts
          path: |
            before_start.png
            after_start.png
            final_screen.xml

  summarize:
    runs-on: ubuntu-latest
    needs: build  # Wait until the build job completes
    steps:
      - name: Download UI Test Artifacts
        uses: actions/download-artifact@v4
        with:
          name: UI-Test-Artifacts
          path: ./artifacts

      - name: Create Job Summary
        run: |
          BEFORE=$(base64 ./artifacts/before_start.png | tr -d '\n')
          AFTER=$(base64 ./artifacts/after_start.png | tr -d '\n')

          echo "## Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Display the two images side by side in a table
          echo "<table><tr>" >> $GITHUB_STEP_SUMMARY
          echo "<td><img src='data:image/png;base64,$BEFORE' width='300'></td>" >> $GITHUB_STEP_SUMMARY
          echo "<td><img src='data:image/png;base64,$AFTER' width='300'></td>" >> $GITHUB_STEP_SUMMARY
          echo "</tr></table>" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**XML Dump:** final_screen.xml (download from artifacts)" >> $GITHUB_STEP_SUMMARY