name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --repo-update || true

    - name: Set Default Scheme
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV
        echo "Using default scheme: $default"

    - name: Build the app (unsigned)
      run: |
        xcodebuild archive \
          -project "MASTestApp.xcodeproj" \
          -scheme $DEFAULT_SCHEME \
          -archivePath $GITHUB_WORKSPACE/build/MASTestApp.xcarchive \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Create IPA manually
      run: |
        cd $GITHUB_WORKSPACE/build/MASTestApp.xcarchive/Products
        mv Applications Payload
        zip -r MASTestApp.zip Payload
        mv MASTestApp.zip MASTestApp.ipa
        mv MASTestApp.ipa $GITHUB_WORKSPACE/output/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unsigned-iOS-App
        path: output/MASTestApp.ipa
