name: Xcode - Build, Run & Screenshot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Run and Capture Screenshot on iOS Simulator
    runs-on: macos-latest
    env:
      BUNDLE_IDENTIFIER: com.example.MASTestApp  # <-- Update this with your actual bundle identifier
      PLATFORM: "iOS Simulator"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "$default" > default
          echo "Using default scheme: $default"

      - name: Build App
        env:
          scheme: ${{ 'default' }}
        run: |
          # Select the first available iPhone device from xctrace output
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          if ls -A | grep -iq "\.xcworkspace$"; then
            filetype_parameter="workspace"
            file_to_build=$(ls -A | grep -i "\.xcworkspace$")
          else
            filetype_parameter="project"
            file_to_build=$(ls -A | grep -i "\.xcodeproj$")
          fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$PLATFORM,name=$device"

      - name: Install and Launch App on Simulator
        run: |
          # Wait for the simulator to be ready
          sleep 5
          # Attempt to locate the built .app file in DerivedData
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "Error: Could not find the built .app file."
            exit 1
          fi
          echo "Installing app from: $APP_PATH"
          xcrun simctl install booted "$APP_PATH"
          echo "Launching app with bundle identifier $BUNDLE_IDENTIFIER"
          xcrun simctl launch booted "$BUNDLE_IDENTIFIER"

      - name: Capture Screenshot
        run: |
          # Wait for the app to fully launch (adjust delay as needed)
          sleep 10
          xcrun simctl io booted screenshot screenshot.png

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Screenshot
          path: screenshot.png
